name: Deploy File Ripper to AWS

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'


jobs:
  deploy:
    name: full-system-deploy
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: |
          sudo python -m pip install --upgrade pip

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::264067133037:role/file-ripper-process-deploy
          aws-region: us-east-1

      - name: Deploy entrypoint
        run: |
          pip install -r requirements-dev.txt
          cd entrypoint
          pip install -r requirements.txt
          chalice deploy --stage dev

      - name: Deploy determine_definition
        run: |
          pip install -r requirements-dev.txt
          cd determine_definition
          pip install -r requirements.txt
          chalice deploy --stage dev
